version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    container_name: chat_app_server
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    environment:
      SERVER_MONGO_URI: mongodb://mongo_db:27017/chat-mobile-app
    depends_on:
      - mongo_db

volumes:
  mongo_db: { }
